env: mpe

env_args:
  n_reds: 10
  n_blues: 10
  map_name: '10vs10'
  id_embedding_size: 2
  max_time_step: 500
  time_per_step: 6
  frame_per_step: 6
  battlefield_height: 4.0
  view_rad: 600.0
  communicate_rad: 200.0
  collision_distance: 10.0
  cold_boot_step: 10
  max_observed_allies: 5
  max_observed_enemies: 5
  render: True
  battlefield_size_x: 800.0
  battlefield_size_y: 800.0
  move_amount: 5.0
  track_accleration: 2.0
  replay_path: "TEMP/render"
  debug: False
  obs_last_action: False
  obs_timestep_number: False
  obs_id_embedding: True
  obs_include_ally: False
  obs_instead_of_state: False
  obs_own_position: True
  obs_own_direction: True
  state_last_action: False
  state_timestep_number: False
  state_include_enemy: False
  state_id_embedding: Ture
  reward_sparse: False
  reward_win: 200
  reward_defeat: 0
  reward_scale: True
  reward_scale_rate: 20
  reward_collied_value: 10
  reward_outofbound_value: 0
  reward_death_scale: 0.5

test_greedy: True
test_nepisode: 32
test_intervel: 10000
log_intervel: 10000
runner_log_intervel: 10000
learner_log_intervel: 10000
t_max: 2050000