env: mpe

env_args:
  map_name: '50vs50'
  id_embedding_size: 2
  time_per_step: 6
  frame_per_step: 6
  view_rad: 600.0
  communicate_rad: 200.0
  collision_distance: 5.0
  cold_boot_step: 10
  max_observed_allies: 5
  max_observed_enemies: 5
  render: False
  move_amount: 6.0
  track_accleration: 1.5
  replay_dir: "RenderReplay"
  debug: False
  obs_last_action: True
  obs_timestep_number: False
  obs_id_embedding: False
  obs_include_ally: True
  obs_instead_of_state: False
  obs_own_position: True
  obs_own_direction: True
  state_last_action: False
  state_timestep_number: False
  state_include_enemy: True
  state_id_embedding: False
  reward_sparse: False
  reward_win: 200
  reward_defeat: 0
  reward_scale: True
  reward_scale_rate: 20
  reward_collied_value: 10
  reward_death_scale: 0.5

test_greedy: True
test_nepisode: 32
test_intervel: 10000
log_intervel: 10000
runner_log_intervel: 10000
learner_log_intervel: 10000
t_max: 2050000